= gerrit仓库整理说明 =

根据之前邮件的说明(http://lists.163.org/pipermail/openstack/2012-October/000126.html)
昨天完成了把我们的scm上的gerrit仓库和社区github仓库的整合, 把我们的仓库从openstack-f/xxx迁移到了openstack/xxx下.
目前在我们scm上整理后的新仓库中, 是可以看到官方的git历史的.


== 整理后现在scm上的repo说明 ==

=== 从openstack-f迁移到openstack下的新建的repo ===
    openstack/gauge
    openstack/nurse
    openstack/postman
    openstack/umbrella
    openstack/wallet


=== 其他新建的repo ===
    openstack/openstack-manuals

    openstack/cinder
    openstack/python-cinderclient

    openstack/python-keystoneclient
    openstack/python-quantumclient

    openstack/melange
    openstack/python-melangeclient

    openstack/horizon


=== 将要删除的repo ===
请大家做好备份工作, 2个星期以后如果没有问题会删除掉下面的
repo(openstack-f下的所有repo)

    openstack-f/cinder
    openstack-f/gauge
    openstack-f/glance
    openstack-f/keystone
    openstack-f/nova
    openstack-f/nurse
    openstack-f/postman
    openstack-f/python-cinderclient
    openstack-f/python-glanceclient
    openstack-f/python-keystoneclient
    openstack-f/python-novaclient
    openstack-f/python-quantumclient
    openstack-f/quantum
    openstack-f/umbrella
    openstack-f/vollib
    openstack-f/wallet
    openstack-manuals


=== 和官方同步的git repo ===
之前向openstack-f下的repo提交过的review, 需要重新向下面说明的新review分支
重新提交一遍.

    openstack/nova
        master
        stable/folsom       --> 和官方github同步
        stable/essex

        essex-ntse          --> essex版本提交review用的分支
        essex-ntse-clean    --> essex版本清理干净后给SA打包用的分支
        folsom-ntse         --> folsom版本提交review用的分支


    openstack/glance
        master
        stable/folsom       --> 和官方github同步
        stable/essex

        essex-ntse          --> essex版本提交review用的分支
        essex-ntse-clean    --> essex版本清理干净后给SA打包用的分支
        folsom-ntse         --> folsom版本提交review用的分支


    openstack/keystone
        master
        stable/folsom       --> 和官方github同步
        stable/essex


    openstack/quantum
        master
        stable/folsom       --> 和官方github同步
        stable/essex


    openstack/cinder
        master
        stable/folsom       --> 和官方github同步


    openstack/horizon
        master
        stable/folsom       --> 和官方github同步
        stable/essex


    openstack/melange
        master
        stable/essex       --> 和官方github同步


    openstack/openstack-manuals
        master
        stable/folsom       --> 和官方github同步
        stable/essex


    openstack/python-novaclient
        master              --> 和官方github同步


    openstack/python-glanceclient
        master              --> 和官方github同步
        folsom-ntse         --> folsom版本提交review用的分支


    openstack/python-keystoneclient
        master              --> 和官方github同步


    openstack/python-cinderclient
        master              --> 和官方github同步


    openstack/python-melangeclient
        master              --> 和官方github同步


    openstack/python-quantumclient
        master              --> 和官方github同步

